# -*- coding: utf-8 -*-
"""YouTube Audio Downloader and Password Generator and Manager .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YFECDh3pxcikc37bZvTcXRDUN88GL_Dx

**TASK-2(Part-1)**

YouTube Downloader[Audio of any video]
"""

pip install youtube_dl

from youtube_dl import YoutubeDL
from youtube_dl import YoutubeDL
Audio_Downloder = YoutubeDL({'format':'bestaudio'})
#added my fav song link you can add yors:D
Link = 'https://youtu.be/MU0Yp0qmYEs'
Audio_Downloder.extract_info(Link)

"""TASK-2[Part-2]

PASSWORD GENERATOR AND MANAGER
"""

import random
Alpha = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ123456789!@€$#%({)}],/<\.>[*^&"

while 1:
    password_len = int(input("Lenght of password? :"))
    count = int(input("Number of passwords you need? "))
    for x in range(0, count):
        password = ""
        for x in range(0,password_len):
            password_Alpha = random.choice(Alpha)
            password      = password + password_Alpha
        print("There you go!! : ",password)

import os
username = "nikk" @niharika{type:"string"}
password = "Heyyy![[[[]]]" {type:"string"}
print("Creating User and Setting it up")

# Creation of user
os.system(f"useradd -m {username}")

# Add user to sudo group
os.system(f"adduser {username} sudo")
    
# Set password of user to 'root'
os.system(f"echo '{username}:{password}' | sudo chpasswd")

# Change default shell from sh to bash
os.system("sed -i 's/\/bin\/sh/\/bin\/bash/g' /etc/passwd")

print("User Created and Configured")

